### ISSUE TITLE
1.12.2 Incompatibility

### ISSUE THREAD

**Issue by ChrisChinchilla** [yitzchak/linter-spell#36] opened 2016-11-12 09:51 UTC
I'm not 100% sure if this is a valid issue or not, but I recently updated Atom to the version released in the past couple of days, and also did some laptop spring cleaning, so maybe I deleted something.

But now I can't get spell checking to work and receive this error:
<img width="1121" alt="screenshot 2016-11-12 10 52 32" src="https://cloud.githubusercontent.com/assets/42080/20236976/269fbc62-a8c6-11e6-9d70-0e7519d98e07.png">

**Comment by yitzchak** [comment] 2016-11-12 11:56
Looks like it is having a hard time running `aspell`? Can you check to make sure is in the search path?

**Comment by ChrisChinchilla** [comment] 2016-11-12 15:41
@yitzchak I don't think so as I don't remember having this issue with aspell in Atom before, could you give an example of settings that you would expect? If so, I may make a PR against the read me to make that a bit clearer.

**Comment by yitzchak** [comment] 2016-11-12 15:55
I suspect the error is coming from the call to `aspell dicts` which should return a list of dictionaries. I added an error message and a null check. Try to update to v0.12.4. It probably won't fix the issue, but it may tell us more.

**Comment by ChrisChinchilla** [comment] 2016-11-12 16:29
@yitzchak I got his working again by specifying the complete path to aspell (i.e /usr/local/bin/aspell) and deleting all the settings for languages and dictionaries. I'm now unsure if this was a bug or not, maybe see if anyone else gets it :/

**Comment by yitzchak** [comment] 2016-11-12 16:31
@ChrisChinchilla Glad you got it working again. I'll dig around and see if there is a root cause.

**Closed as completed** 2017-03-16 09:55 UTC
